export const RESET_CONTACT_FORM = 'RESET_CONTACT_FORM';
export const SEND_CONTACT_FORM = 'SEND_CONTACT_FORM';
export const SELECT_ACTIVE_PAGE = 'SELECT_ACTIVE_PAGE';
export const VALIDATE_RECAPTCHA = 'VALIDATE_RECAPTCHA';
